### ISSUE TITLE
recaptcha proethos 2

### ISSUE THREAD

**Issue by amelgar04** [marcie-n/paho#3]
I need Help with recaptcha proethos 2.

![Captura de pantalla 2022-11-21 150338](https://user-images.githubusercontent.com/118770296/203148098-1be1cbd7-4c1d-494c-876c-46e6d887e74f.png)

**Comment by marcie-n** [comment]
which version of ProEthos are you using? Please confirm, as this may be due to an older version of the site.

**Comment by amelgar04** [comment]
Hi, Im using this one:

***@***.***

Saludos.

Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103
***@***.***

De: Marcie N ***@***.***>
Enviado el: lunes, noviembre 21, 2022 3:17 PM
Para: marcie-n/paho ***@***.***>
CC: Abilio A. Melgar Ubarte ***@***.***>; Author ***@***.***>
Asunto: Re: [marcie-n/paho] recaptcha proethos 2 (Issue #3)


which version of ProEthos are you using? Please confirm, as this may be due to an older version of the site.

**Comment by marcie-n** [comment]
sorry, nothing came up when you entered the data, only asterisks. could you type in the version please, or send a screenshot as you did in the first comment. 
Thanks!

**Comment by amelgar04** [comment]
Yes, sorry! V1.10.0

Saludos.

Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103
***@***.***

De: Marcie N ***@***.***>
Enviado el: lunes, noviembre 21, 2022 4:26 PM
Para: marcie-n/paho ***@***.***>
CC: Abilio A. Melgar Ubarte ***@***.***>; Author ***@***.***>
Asunto: Re: [marcie-n/paho] recaptcha proethos 2 (Issue #3)


sorry, nothing came up when you entered the data, only asterisks. could you type in the version please, or send a screenshot as you did in the first comment.
Thanks!

**Comment by marcie-n** [comment]
@wilsonmoura puedes ver este issue [#3](https://github.com/marcie-n/paho/issues/3)

**Comment by wilsonmoura** [comment]
@amelgar04 In order for recaptcha to work correctly, you need to generate a key in [Google reCaptcha](https://www.google.com/recaptcha/) and adjust the settings in `System Management >> Configurations >> Google Analytics Code`. See below an image of the settings page that needs to be adjusted:

![Configurations-Proethos2](https://user-images.githubusercontent.com/3779520/203196062-7d023f6f-c984-46f7-9b3a-2854c2d5feae.png)

**Comment by amelgar04** [comment]
Wilson, i made the change and doenst resolve the issue.

Saludos.

Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103
***@***.***

De: Wilson da Silva Moura ***@***.***>
Enviado el: lunes, noviembre 21, 2022 8:44 PM
Para: marcie-n/paho ***@***.***>
CC: Abilio A. Melgar Ubarte ***@***.***>; Mention ***@***.***>
Asunto: Re: [marcie-n/paho] recaptcha proethos 2 (Issue #3)


@amelgar04<https://github.com/amelgar04> In order for recaptcha to work correctly, you need to generate a key in Google reCaptcha<https://www.google.com/recaptcha/> and adjust the settings in System Management >> Configurations >> Google Analytics Code. See below an image of the settings page that needs to be adjusted:

[Configurations-Proethos2]<https://user-images.githubusercontent.com/3779520/203196062-7d023f6f-c984-46f7-9b3a-2854c2d5feae.png>

**Comment by amelgar04** [comment]
Hola Wilson, puede darme luces del servidor de correo a configurar para proethos, he configurado el sendmail, pero al realizar pruebas el correo no llega, y los log dicen:


  1.  DNS no disponible.
  2.  Dominio de remitente no existe.


Quisiera saber que archivos revisar además de los .mc . cf .cnf

Saludos.

Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103
***@***.***

De: Abilio A. Melgar Ubarte
Enviado el: martes, noviembre 22, 2022 8:22 AM
Para: marcie-n/paho ***@***.***>; marcie-n/paho ***@***.***>
CC: Mention ***@***.***>
Asunto: RE: [marcie-n/paho] recaptcha proethos 2 (Issue #3)

Wilson, i made the change and doenst resolve the issue.

Saludos.

Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103
***@***.***

De: Wilson da Silva Moura ***@***.******@***.***>>
Enviado el: lunes, noviembre 21, 2022 8:44 PM
Para: marcie-n/paho ***@***.******@***.***>>
CC: Abilio A. Melgar Ubarte ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Asunto: Re: [marcie-n/paho] recaptcha proethos 2 (Issue #3)


@amelgar04<https://github.com/amelgar04> In order for recaptcha to work correctly, you need to generate a key in Google reCaptcha<https://www.google.com/recaptcha/> and adjust the settings in System Management >> Configurations >> Google Analytics Code. See below an image of the settings page that needs to be adjusted:

[Configurations-Proethos2]<https://user-images.githubusercontent.com/3779520/203196062-7d023f6f-c984-46f7-9b3a-2854c2d5feae.png>

**Comment by wilsonmoura** [comment]
@amelgar04 el enlace correcto para generar las claves del reCapctha es https://developers.google.com/recaptcha

Por favor intente configurar el reCaptcha siguiendo las instrucciones que están disponibles en este enlace.
