### ISSUE TITLE
Servidor de correos proethos2

### ISSUE THREAD

**Issue by amelgar04** [marcie-n/paho#4]
Que archivos debo configurar para lograr el envío de correos en la plataforma.

**Comment by amelgar04** [comment]
Hola @marcie-n pueden ayudarme a qué no servidor envíe notificaciones por correo.

**Comment by marcie-n** [comment]
Estimado, según entiendo, los templates de los correos deben venir en la versión master. Favor de confirmar si están. Se encuentran aquí:
1. desde el menu [administración del sistema]
2. mail messages
![Screen Shot 2022-11-30 at 9 21 48 AM](https://user-images.githubusercontent.com/30055654/204820635-128ce479-f86d-40af-ab0d-97ab405a27d6.png)
3. acceder el listado de los mails
![Screen Shot 2022-11-30 at 9 22 07 AM](https://user-images.githubusercontent.com/30055654/204820807-5f54684a-1e77-41c2-aa73-437658d72060.png)
4. editar texto de los mails
![Screen Shot 2022-11-30 at 9 22 20 AM](https://user-images.githubusercontent.com/30055654/204820864-7eb8fb7f-598d-4036-be8a-4e3b8004cb74.png)

Si está en blanco, avísame y les pasare una tabla de correos en template.

**Comment by amelgar04** [comment]
Gracias por responder Marcie, estas plantillas están llenas, sin embargo, me gustaría que me las enviaras y comparar.

He estado configurando el servidor ubuntu desde cero, me refiero a que necesito ayuda a confirmar la dirección del remitente, puerto, servidor smtp, ya que he configurado lo que normalmente se hace con un sendmail o postfix y no logro resultados.


Saludos.


Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103


________________________________
De: Marcie N ***@***.***>
Enviado: Wednesday, November 30, 2022 9:25:37 AM
Para: marcie-n/paho ***@***.***>
Cc: Abilio A. Melgar Ubarte ***@***.***>; Author ***@***.***>
Asunto: Re: [marcie-n/paho] Servidor de correos proethos2 (Issue #4)


Estimado, según entiendo, los templates de los correos deben venir en la versión master. Favor de confirmar si están. Se encuentran aquí:

  1.  desde el menu [administración del sistema]
  2.  mail messages
[Screen Shot 2022-11-30 at 9 21 48 AM]<https://user-images.githubusercontent.com/30055654/204820635-128ce479-f86d-40af-ab0d-97ab405a27d6.png>
  3.  acceder el listado de los mails
[Screen Shot 2022-11-30 at 9 22 07 AM]<https://user-images.githubusercontent.com/30055654/204820807-5f54684a-1e77-41c2-aa73-437658d72060.png>
  4.  editar texto de los mails
[Screen Shot 2022-11-30 at 9 22 20 AM]<https://user-images.githubusercontent.com/30055654/204820864-7eb8fb7f-598d-4036-be8a-4e3b8004cb74.png>

Si está en blanco, avísame y les pasare una tabla de correos en template.

**Comment by wilsonmoura** [comment]
@amelgar04 la configuración de envío de correo electrónico se debe ajustar en el archivo `app/config/parameters.yml`:

    mailer_transport: smtp
    mailer_host: 127.0.0.1 # Cambiar para el host SMTP
    mailer_user: null # Cambiar al usuario de la cuenta del host SMTP
    mailer_password: null # Cambiar a la contrasenã de la cuenta del host SMTP

**Comment by amelgar04** [comment]
Buenas tardes Wilson, te agradezco haber contestado, este archivo ya lo tengo configurado con nuestra información y aún así no funciona el envío de correos.


Saludos.


Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103


________________________________
De: Wilson da Silva Moura ***@***.***>
Enviado: Wednesday, November 30, 2022 11:18:36 PM
Para: marcie-n/paho ***@***.***>
Cc: Abilio A. Melgar Ubarte ***@***.***>; Mention ***@***.***>
Asunto: Re: [marcie-n/paho] Servidor de correos proethos2 (Issue #4)


@amelgar04<https://github.com/amelgar04> la configuración de envío de correo electrónico se debe ajustar en el archivo app/config/parameters.yml:

mailer_transport: smtp

mailer_host: 127.0.0.1 # Cambiar para el host SMTP

mailer_user: null # Cambiar al usuario de la cuenta del host SMTP

mailer_password: null # Cambiar a la contrasenã de la cuenta del host SMTP

**Comment by wilsonmoura** [comment]
@amelgar04 creo que es mejor usar otra configuración para enviar correos electrónicos. Por lo tanto, existen otras alternativas que pueden ayudar:

- [PHP mail() Function](https://github.com/bireme/proethos2/blob/master/doc/how-to/how-to-install-proethos2-in-ubuntu-es.md#php-mail-funtion)
- [sendmail](https://github.com/bireme/proethos2/blob/master/doc/how-to/how-to-install-proethos2-in-ubuntu-es.md#sendmail)

Estas alternativas utilizan el propio servidor como host para el envío de correos electrónicos. Recomendamos probar una de estas alternativas y ver cuál es probable que resuelva este problema.

**Comment by amelgar04** [comment]
Hola Wilson, ya he intentado con sendmail, sin resultados. Seguiré probando otras opciones. me gustaría ver si tienen disponibilidad para otra revisión del servidor para el 14 o 15 de diciembre.


Saludos.


Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103


________________________________
De: Wilson da Silva Moura ***@***.***>
Enviado: Friday, December 9, 2022 11:42:31 PM
Para: marcie-n/paho ***@***.***>
Cc: Abilio A. Melgar Ubarte ***@***.***>; Mention ***@***.***>
Asunto: Re: [marcie-n/paho] Servidor de correos proethos2 (Issue #4)


@amelgar04<https://github.com/amelgar04> creo que es mejor usar otra configuración para enviar correos electrónicos. Por lo tanto, existen otras alternativas que pueden ayudar:

  *   PHP mail() Function<https://github.com/bireme/proethos2/blob/master/doc/how-to/how-to-install-proethos2-in-ubuntu-es.md#php-mail-funtion> o
  *   sendmail<https://github.com/bireme/proethos2/blob/master/doc/how-to/how-to-install-proethos2-in-ubuntu-es.md#sendmail>

Estas alternativas utilizan el propio servidor como host para el envío de correos electrónicos. Recomendamos probar una de estas alternativas y ver cuál es probable que resuelva este problema.

**Comment by wilsonmoura** [comment]
@amelgar04 para las otras alternativas sugeridas ([PHP mail() Function](https://github.com/bireme/proethos2/blob/master/doc/how-to/how-to-install-proethos2-in-ubuntu-es.md#php-mail-funtion) o [sendmail](https://github.com/bireme/proethos2/blob/master/doc/how-to/how-to-install-proethos2-in-ubuntu-es.md#sendmail)), según la documentación disponible en cada enlace, es necesario instalar algunos paquetes para que el envío de correos electrónicos funcione correctamente. Por lo tanto, recomendamos probar todas las sugerencias de configuración para identificar cuál resuelve este problema.

**Comment by wilsonmoura** [comment]
@amelgar04 para la reunión, estoy disponible para el día 14 por la mañana y el 15 por la tarde.

**Comment by amelgar04** [comment]
Perfecto, podemos hacer la reunión a las 9am del día de hoy?


Saludos.


Abilio A. Melgar Ubarte
Jefe de la Oficina de Informática
Tel: (507)517-00103| Ext. 1103


________________________________
De: Wilson da Silva Moura ***@***.***>
Enviado: Tuesday, December 13, 2022 7:05:51 PM
Para: marcie-n/paho ***@***.***>
Cc: Abilio A. Melgar Ubarte ***@***.***>; Mention ***@***.***>
Asunto: Re: [marcie-n/paho] Servidor de correos proethos2 (Issue #4)


@amelgar04<https://github.com/amelgar04> para la reunión, estoy disponible para el día 14 por la mañana y el 15 por la tarde.

**Comment by wilsonmoura** [comment]
@amelgar04 Según la conversación por correo electrónico, nos complace saber que pudo configurar los ajustes para enviar mensajes por correo electrónico en la plataforma ProEthos2. Creo que sería interesante compartir esta solución para que podamos ayudar a otros usuarios que también pueden tener el mismo problema. ¡Gracias de antemano por su apoyo!
